# Generated by Django 2.2.1 on 2019-06-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_roomaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='Здесь должна находиться инфлрмация о пользователе', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, default='Информация отсутствует', max_length=200, null=True),
        ),
    ]
