# Generated by Django 2.2.1 on 2019-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20190602_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='Здесь должна находиться информация о пользователе', null=True),
        ),
    ]
